/**
 * MultiLegFlightEditor
 * 
 * Auto-generates flight leg input slots based on multi-city destinations.
 * For a trip ATL → London → Paris → ATL, generates:
 *   Leg 1: ATL → LHR (outbound)
 *   Leg 2: LHR → CDG (inter-city)
 *   Leg 3: CDG → ATL (return)
 * 
 * Also supports adding custom legs (e.g. connecting flights).
 * For single-city trips, falls back to outbound + optional return.
 */

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Plane, Train, Bus, Car, Ship, Plus, Trash2, ChevronDown, ChevronUp,
  ArrowRight, Upload, GripVertical, MapPin,
} from 'lucide-react';
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragEndEvent,
} from '@dnd-kit/core';
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { AirportAutocomplete } from '@/components/common/AirportAutocomplete';
import { AirlineAutocomplete } from '@/components/common/AirlineAutocomplete';
import { cn } from '@/lib/utils';
import type { ManualFlightEntry } from '@/components/itinerary/AddBookingInline';
import type { TripDestination } from '@/types/multiCity';

export type LegTransportType = 'flight' | 'train' | 'bus' | 'car' | 'ferry';

export interface FlightLegSlot {
  /** Unique identifier for this slot */
  id: string;
  /** Index of the city transition this slot belongs to (-1 for custom legs) */
  transitionIndex: number;
  /** Label shown to the user, e.g. "London → Paris" */
  label: string;
  /** Whether this is an outbound, inter-city, or return leg */
  legType: 'outbound' | 'intercity' | 'return' | 'custom';
  /** Transport type for this slot */
  transportType: LegTransportType;
  /** The flight data for this slot */
  flight: ManualFlightEntry;
  /** Pre-filled from/to based on city airports */
  suggestedFrom?: string;
  suggestedTo?: string;
  /** Whether this slot was auto-generated or manually added */
  isAutoGenerated: boolean;
  /** Whether details section is expanded */
  isExpanded: boolean;
  /** Additional connecting flights grouped with this slot */
  connectionLegs?: ManualFlightEntry[];
}

interface MultiLegFlightEditorProps {
  destinations: TripDestination[];
  startDate: string;
  endDate: string;
  /** Transport selections from InterCityTransportComparison (transition index → type) */
  transportSelections?: Record<number, { type: LegTransportType }>;
  /** Called whenever legs change */
  onLegsChange: (legs: ManualFlightEntry[]) => void;
  /** Called when user changes transport mode for an intercity leg */
  onTransportModeChange?: (transitionIndex: number, mode: LegTransportType) => void;
  /** Called to open the import modal */
  onOpenImport: () => void;
  /** Current outbound/return/additional legs from parent (for init) */
  initialOutbound?: ManualFlightEntry;
  initialReturn?: ManualFlightEntry;
  initialAdditionalLegs?: ManualFlightEntry[];
  /** Explicitly imported legs from modal; applied by index to visible slots */
  importedLegs?: ManualFlightEntry[];
  /** Incremented on each import to force deterministic re-apply */
  importNonce?: number;
}

const TRANSPORT_ICONS: Record<LegTransportType, typeof Plane> = {
  flight: Plane,
  train: Train,
  bus: Bus,
  car: Car,
  ferry: Ship,
};

const TRANSPORT_LABELS: Record<LegTransportType, string> = {
  flight: 'Flight',
  train: 'Train',
  bus: 'Bus',
  car: 'Drive',
  ferry: 'Ferry',
};

function emptyFlight(date?: string): ManualFlightEntry {
  return {
    airline: '',
    flightNumber: '',
    departureAirport: '',
    arrivalAirport: '',
    departureTime: '',
    arrivalTime: '',
    departureDate: date || '',
  };
}

let slotIdCounter = 0;
function nextSlotId() {
  return `leg-slot-${++slotIdCounter}`;
}

function hasFlightContent(f?: ManualFlightEntry): boolean {
  if (!f) return false;
  return Boolean(
    f.airline ||
    f.flightNumber ||
    f.departureAirport ||
    f.arrivalAirport ||
    f.departureTime ||
    f.arrivalTime ||
    f.price
  );
}

function isSameFlightEntry(a: ManualFlightEntry, b: ManualFlightEntry): boolean {
  return (
    (a.airline || '') === (b.airline || '') &&
    (a.flightNumber || '') === (b.flightNumber || '') &&
    (a.departureAirport || '') === (b.departureAirport || '') &&
    (a.arrivalAirport || '') === (b.arrivalAirport || '') &&
    (a.departureTime || '') === (b.departureTime || '') &&
    (a.arrivalTime || '') === (b.arrivalTime || '') &&
    (a.departureDate || '') === (b.departureDate || '') &&
    Number(a.price || 0) === Number(b.price || 0)
  );
}

function uniqueMeaningfulLegs(legs: ManualFlightEntry[]): ManualFlightEntry[] {
  const unique: ManualFlightEntry[] = [];

  for (const leg of legs) {
    if (!hasFlightContent(leg)) continue;
    if (unique.some((existing) => isSameFlightEntry(existing, leg))) continue;
    unique.push(leg);
  }

  return unique;
}

/**
 * Generate leg slots from destinations array.
 * For destinations [London, Paris, Rome], generates:
 *   Leg 1: ? → London (outbound)
 *   Leg 2: London → Paris (inter-city)
 *   Leg 3: Paris → Rome (inter-city)
 *   Leg 4: Rome → ? (return)
 */
function generateSlotsFromDestinations(
  destinations: TripDestination[],
  startDate: string,
  endDate: string,
  transportSelections?: Record<number, { type: LegTransportType }>,
): FlightLegSlot[] {
  const slots: FlightLegSlot[] = [];

  if (destinations.length === 0) return slots;

  const firstDest = destinations[0];
  const lastDest = destinations[destinations.length - 1];

  // Outbound: Home → First City
  slots.push({
    id: nextSlotId(),
    transitionIndex: -1,
    label: `Outbound → ${firstDest.city}`,
    legType: 'outbound',
    transportType: 'flight',
    flight: emptyFlight(startDate),
    suggestedTo: firstDest.airportCode || '',
    isAutoGenerated: true,
    isExpanded: false,
  });

  // Inter-city transitions
  for (let i = 0; i < destinations.length - 1; i++) {
    const from = destinations[i];
    const to = destinations[i + 1];
    const transportType = transportSelections?.[i]?.type || 'flight';
    const travelDate = from.departureDate || '';

    slots.push({
      id: nextSlotId(),
      transitionIndex: i,
      label: `${from.city} → ${to.city}`,
      legType: 'intercity',
      transportType,
      flight: emptyFlight(travelDate),
      suggestedFrom: from.airportCode || '',
      suggestedTo: to.airportCode || '',
      isAutoGenerated: true,
      isExpanded: false,
    });
  }

  // Return: Last City → Home
  slots.push({
    id: nextSlotId(),
    transitionIndex: -1,
    label: `${lastDest.city} → Return`,
    legType: 'return',
    transportType: 'flight',
    flight: emptyFlight(endDate),
    suggestedFrom: lastDest.airportCode || '',
    isAutoGenerated: true,
    isExpanded: false,
  });

  return slots;
}

export default function MultiLegFlightEditor({
  destinations,
  startDate,
  endDate,
  transportSelections,
  onLegsChange,
  onOpenImport,
  initialOutbound,
  initialReturn,
  initialAdditionalLegs,
  importedLegs,
  importNonce,
  onTransportModeChange,
}: MultiLegFlightEditorProps) {
  const [slots, setSlots] = useState<FlightLegSlot[]>([]);
  const [initialized, setInitialized] = useState(false);
  const lastAppliedNonce = useRef<number>(0);
  const onLegsChangeRef = useRef(onLegsChange);
  /** Stable signature of last emitted legs — prevents redundant parent updates */
  const lastEmittedSignature = useRef<string>('');

  useEffect(() => {
    onLegsChangeRef.current = onLegsChange;
  }, [onLegsChange]);

  // Generate slots on mount / destination change
  useEffect(() => {
    if (initialized) return;

    const autoSlots = generateSlotsFromDestinations(destinations, startDate, endDate, transportSelections);

    // Merge with initial data if available
    if (initialOutbound && (initialOutbound.arrivalTime || initialOutbound.departureAirport)) {
      if (autoSlots.length > 0 && autoSlots[0].legType === 'outbound') {
        autoSlots[0].flight = { ...initialOutbound };
      }
    }
    if (initialReturn && (initialReturn.departureTime || initialReturn.departureAirport)) {
      const returnSlot = autoSlots.find(s => s.legType === 'return');
      if (returnSlot) {
        returnSlot.flight = { ...initialReturn };
      }
    }
    if (initialAdditionalLegs && initialAdditionalLegs.length > 0) {
      const interCitySlots = autoSlots.filter(s => s.legType === 'intercity');
      initialAdditionalLegs.forEach((leg, i) => {
        if (i < interCitySlots.length) {
          interCitySlots[i].flight = { ...leg };
        }
      });
    }

    setSlots(autoSlots);
    setInitialized(true);
  }, [destinations, startDate, endDate, transportSelections, initialized, initialOutbound, initialReturn, initialAdditionalLegs]);

  // Sync transport type selections from InterCityTransportComparison into existing slots
  useEffect(() => {
    if (!initialized || !transportSelections) return;
    setSlots(prev => {
      let changed = false;
      const updated = prev.map(s => {
        if (s.legType === 'intercity' && s.transitionIndex >= 0) {
          const sel = transportSelections[s.transitionIndex];
          if (sel && sel.type !== s.transportType) {
            changed = true;
            return { ...s, transportType: sel.type };
          }
        }
        return s;
      });
      return changed ? updated : prev;
    });
  }, [initialized, transportSelections]);

  // Rehydrate slots when parent receives imported/loaded legs after initial mount
  useEffect(() => {
    if (!initialized) return;

    // If a new import nonce is pending, let the import effect be the sole authority.
    const hasPendingImportApply = Boolean(
      importNonce &&
      importedLegs &&
      importedLegs.length > 0 &&
      importNonce !== lastAppliedNonce.current
    );
    if (hasPendingImportApply) return;

    // Skip if the current import has already been applied.
    if (importNonce && importNonce === lastAppliedNonce.current) return;

    const incomingLegs: ManualFlightEntry[] = [
      ...(hasFlightContent(initialOutbound) ? [initialOutbound!] : []),
      ...((initialAdditionalLegs || []).filter(hasFlightContent)),
      ...(hasFlightContent(initialReturn) ? [initialReturn!] : []),
    ];

    if (incomingLegs.length === 0) return;

    setSlots((prev) => {
      const flightSlotIndexes = prev
        .map((slot, idx) => ({ slot, idx }))
        .filter(({ slot }) => slot.transportType === 'flight')
        .map(({ idx }) => idx);

      if (flightSlotIndexes.length === 0) return prev;

      const next = [...prev];
      let changed = false;

      // Fill existing flight slots first
      incomingLegs.slice(0, flightSlotIndexes.length).forEach((leg, i) => {
        const slotIndex = flightSlotIndexes[i];
        const current = next[slotIndex].flight;
        if (!isSameFlightEntry(current, leg)) {
          next[slotIndex] = {
            ...next[slotIndex],
            flight: {
              ...current,
              ...leg,
            },
          };
          changed = true;
        }
      });

      // If there are more incoming legs than existing slots, insert them as new custom slots
      if (incomingLegs.length > flightSlotIndexes.length) {
        const extraLegs = incomingLegs.slice(flightSlotIndexes.length);
        const returnIdx = next.findIndex(s => s.legType === 'return');
        const insertAt = returnIdx >= 0 ? returnIdx : next.length;
        
        const newSlots: FlightLegSlot[] = extraLegs.map(leg => ({
          id: nextSlotId(),
          transitionIndex: -1,
          label: `${leg.departureAirport || '?'} → ${leg.arrivalAirport || '?'}`,
          legType: 'custom' as const,
          transportType: 'flight' as LegTransportType,
          flight: { ...leg },
          isAutoGenerated: false,
          isExpanded: true,
        }));

        next.splice(insertAt, 0, ...newSlots);
        changed = true;
      }

      return changed ? next : prev;
    });
  }, [initialized, initialOutbound, initialAdditionalLegs, initialReturn, importNonce, importedLegs]);

  // Deterministically apply last import to visible slots using classification-aware matching
  useEffect(() => {
    if (!initialized || !importedLegs || importedLegs.length === 0 || !importNonce) return;
    lastAppliedNonce.current = importNonce;

    setSlots((prev) => {
      // Remove stale custom slots created by previous imports.
      // Keep only explicit user-added custom rows.
      const baseSlots = prev.filter((slot) => {
        if (slot.legType !== 'custom') return true;
        return slot.label === 'Additional Flight';
      });

      const next = [...baseSlots];
      let changed = baseSlots.length !== prev.length;

      const isLegAlreadyRepresented = (leg: ManualFlightEntry, slotsToCheck: FlightLegSlot[]) =>
        slotsToCheck.some((slot) => slot.transportType === 'flight' && isSameFlightEntry(slot.flight, leg));

      // Group imported legs by classification
      const interDestLegs = importedLegs.filter((l) => l.classification === 'INTER_DESTINATION');

      // Separate true outbound/return from their connections
      const primaryOutbound = importedLegs.find((l) => l.classification === 'OUTBOUND');
      const outboundConnections = primaryOutbound?.connectionGroup != null
        ? importedLegs.filter((l) => l.classification === 'CONNECTION' && l.connectionGroup === primaryOutbound.connectionGroup)
        : [];
      const primaryReturn = importedLegs.find((l) => l.classification === 'RETURN');
      const returnConnections = primaryReturn?.connectionGroup != null
        ? importedLegs.filter((l) => l.classification === 'CONNECTION' && l.connectionGroup === primaryReturn.connectionGroup)
        : [];

      // Track which imported legs have been placed to avoid duplicates
      const placedLegIds = new Set<number>();

      // Map primary legs to existing slots
      next.forEach((slot, idx) => {
        if (slot.transportType !== 'flight') return;

        let matchedLeg: ManualFlightEntry | undefined;
        let matchedIdx = -1;

        if (slot.legType === 'outbound' && primaryOutbound) {
          matchedLeg = primaryOutbound;
          matchedIdx = importedLegs.indexOf(primaryOutbound);
        } else if (slot.legType === 'return' && primaryReturn) {
          matchedLeg = primaryReturn;
          matchedIdx = importedLegs.indexOf(primaryReturn);
        } else if (slot.legType === 'intercity') {
          // Match inter-destination legs by airport code
          const found = interDestLegs.find((l) =>
            (l.departureAirport && slot.suggestedFrom && l.departureAirport === slot.suggestedFrom) ||
            (l.arrivalAirport && slot.suggestedTo && l.arrivalAirport === slot.suggestedTo)
          );
          if (found) {
            matchedLeg = found;
            matchedIdx = importedLegs.indexOf(found);
          }
        }

        // Fallback: if no classification match, try airport-code matching
        if (!matchedLeg && slot.transportType === 'flight') {
          const found = importedLegs.find((l, li) =>
            !placedLegIds.has(li) && !l.classification && (
              (l.departureAirport && slot.suggestedFrom && l.departureAirport === slot.suggestedFrom) ||
              (l.arrivalAirport && slot.suggestedTo && l.arrivalAirport === slot.suggestedTo)
            )
          );
          if (found) {
            matchedLeg = found;
            matchedIdx = importedLegs.indexOf(found);
          }
        }

        if (matchedLeg && !isSameFlightEntry(slot.flight, matchedLeg)) {
          next[idx] = {
            ...slot,
            isExpanded: true,
            flight: { ...slot.flight, ...matchedLeg },
            connectionLegs: undefined, // Don't nest — we'll add as separate slots
          };
          changed = true;
        }
        if (matchedIdx >= 0) {
          placedLegIds.add(matchedIdx);
        }
      });

      // Insert connection legs as separate slots so they appear in the UI
      const connectionLegsToInsert: { afterLegType: string; legs: ManualFlightEntry[] }[] = [];
      if (outboundConnections.length > 0) {
        outboundConnections.forEach((c) => placedLegIds.add(importedLegs.indexOf(c)));
        connectionLegsToInsert.push({ afterLegType: 'outbound', legs: outboundConnections });
      }
      if (returnConnections.length > 0) {
        returnConnections.forEach((c) => placedLegIds.add(importedLegs.indexOf(c)));
        connectionLegsToInsert.push({ afterLegType: 'return', legs: returnConnections });
      }

      // Also pick up any unplaced legs (no classification or unmatched inter-destination)
      const unplacedLegs = importedLegs.filter((_, i) => !placedLegIds.has(i));
      if (unplacedLegs.length > 0) {
        connectionLegsToInsert.push({ afterLegType: 'outbound', legs: unplacedLegs });
      }

      // Insert connection slots into the array
      for (const group of connectionLegsToInsert) {
        // Find the slot to insert after
        let insertAfterIdx: number;
        if (group.afterLegType === 'return') {
          // Insert before the return slot
          insertAfterIdx = next.findIndex((s) => s.legType === 'return');
          if (insertAfterIdx < 0) insertAfterIdx = next.length;
        } else {
          // Insert after the outbound slot
          insertAfterIdx = next.findIndex((s) => s.legType === 'outbound');
          if (insertAfterIdx >= 0) insertAfterIdx += 1;
          else insertAfterIdx = 1;
        }

        const newConnectionSlots: FlightLegSlot[] = [];
        for (const leg of group.legs) {
          // Prevent duplicates if already mapped or already in the list.
          if (isLegAlreadyRepresented(leg, next) || newConnectionSlots.some((s) => isSameFlightEntry(s.flight, leg))) {
            continue;
          }

          newConnectionSlots.push({
            id: nextSlotId(),
            transitionIndex: -1,
            label: `${leg.classification === 'CONNECTION' ? 'Connection' : 'Flight'}: ${leg.departureAirport || '?'} → ${leg.arrivalAirport || '?'}`,
            legType: 'custom',
            transportType: 'flight',
            flight: { ...leg },
            isAutoGenerated: false,
            isExpanded: true,
          });
        }

        if (newConnectionSlots.length > 0) {
          next.splice(insertAfterIdx, 0, ...newConnectionSlots);
          changed = true;
        }
      }

      if (changed) {
        const emittedLegs = uniqueMeaningfulLegs(next.map((s) => s.flight));
        const sig = emittedLegs.map(l => [l.airline,l.flightNumber,l.departureAirport,l.arrivalAirport,l.departureTime,l.arrivalTime,l.departureDate,l.price,l.isDestinationArrival,l.isDestinationDeparture].join('|')).join('||');
        if (sig !== lastEmittedSignature.current) {
          lastEmittedSignature.current = sig;
          onLegsChangeRef.current(emittedLegs);
        }
      }

      return changed ? next : prev;
    });
  }, [initialized, importNonce, importedLegs]);

  // Sync changes to parent — emit all legs (including non-flight) so data isn't lost
  const syncToParent = useCallback((updatedSlots: FlightLegSlot[]) => {
    const allLegs = uniqueMeaningfulLegs(updatedSlots.map(s => s.flight));
    const sig = allLegs.map(l => [l.airline,l.flightNumber,l.departureAirport,l.arrivalAirport,l.departureTime,l.arrivalTime,l.departureDate,l.price,l.isDestinationArrival,l.isDestinationDeparture].join('|')).join('||');
    if (sig === lastEmittedSignature.current) return;
    lastEmittedSignature.current = sig;
    onLegsChangeRef.current(allLegs);
  }, []);

  const updateSlotFlight = useCallback((slotId: string, patch: Partial<ManualFlightEntry>) => {
    setSlots(prev => {
      const updated = prev.map(s =>
        s.id === slotId ? { ...s, flight: { ...s.flight, ...patch } } : s
      );
      syncToParent(updated);
      return updated;
    });
  }, [syncToParent]);

  const toggleSlotExpanded = useCallback((slotId: string) => {
    setSlots(prev => prev.map(s =>
      s.id === slotId ? { ...s, isExpanded: !s.isExpanded } : s
    ));
  }, []);

  const addCustomLeg = useCallback(() => {
    setSlots(prev => {
      // Insert before the return leg
      const returnIdx = prev.findIndex(s => s.legType === 'return');
      const newSlot: FlightLegSlot = {
        id: nextSlotId(),
        transitionIndex: -1,
        label: 'Additional Flight',
        legType: 'custom',
        transportType: 'flight',
        flight: emptyFlight(),
        isAutoGenerated: false,
        isExpanded: true,
      };
      const updated = [...prev];
      if (returnIdx >= 0) {
        updated.splice(returnIdx, 0, newSlot);
      } else {
        updated.push(newSlot);
      }
      syncToParent(updated);
      return updated;
    });
  }, [syncToParent]);

  const removeSlot = useCallback((slotId: string) => {
    setSlots(prev => {
      const updated = prev.filter(s => s.id !== slotId);
      syncToParent(updated);
      return updated;
    });
  }, [syncToParent]);

  const changeTransportType = useCallback((slotId: string, type: LegTransportType) => {
    setSlots(prev => {
      const updated = prev.map(s =>
        s.id === slotId ? { ...s, transportType: type } : s
      );
      syncToParent(updated);
      // Propagate mode change for intercity legs to parent
      const slot = updated.find(s => s.id === slotId);
      if (slot?.legType === 'intercity' && slot.transitionIndex >= 0 && onTransportModeChange) {
        onTransportModeChange(slot.transitionIndex, type);
      }
      return updated;
    });
  }, [syncToParent, onTransportModeChange]);

  // Route chain summary
  const routeChain = useMemo(() => {
    if (destinations.length < 2) return null;
    const cities = destinations.map(d => d.airportCode || d.city.slice(0, 3).toUpperCase());
    return ['HOME', ...cities, 'HOME'];
  }, [destinations]);

  // Drag and drop reorder
  const pointerSensor = useSensor(PointerSensor, { activationConstraint: { distance: 8 } });
  const keyboardSensor = useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates });
  const sensors = useSensors(pointerSensor, keyboardSensor);
  const slotIds = useMemo(() => slots.map(s => s.id), [slots]);

  const handleDragEnd = useCallback((event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    setSlots(prev => {
      const oldIndex = prev.findIndex(s => s.id === active.id);
      const newIndex = prev.findIndex(s => s.id === over.id);
      if (oldIndex === -1 || newIndex === -1) return prev;
      const reordered = arrayMove(prev, oldIndex, newIndex);
      syncToParent(reordered);
      return reordered;
    });
  }, [syncToParent]);

  // Star marking handlers — toggle on target, clear on others
  const markDestinationArrival = useCallback((slotId: string) => {
    setSlots(prev => {
      const updated = prev.map(s => ({
        ...s,
        flight: {
          ...s.flight,
          isDestinationArrival: s.id === slotId ? !s.flight.isDestinationArrival : false,
        },
      }));
      syncToParent(updated);
      return updated;
    });
  }, [syncToParent]);

  const markDestinationDeparture = useCallback((slotId: string) => {
    setSlots(prev => {
      const updated = prev.map(s => ({
        ...s,
        flight: {
          ...s.flight,
          isDestinationDeparture: s.id === slotId ? !s.flight.isDestinationDeparture : false,
        },
      }));
      syncToParent(updated);
      return updated;
    });
  }, [syncToParent]);

  return (
    <div className="space-y-4 p-4 rounded-xl border border-border bg-card">
      {/* Import button */}
      <div className="flex justify-center border-b border-border pb-3">
        <Button
          variant="ghost"
          size="sm"
          className="text-xs"
          onClick={onOpenImport}
        >
          <Upload className="h-3 w-3 mr-1.5" />
          Paste from airline confirmation
        </Button>
      </div>

      {/* Route chain visualization */}
      {routeChain && routeChain.length > 2 && (
        <div className="flex items-center gap-1 text-xs font-medium text-primary bg-primary/5 rounded-lg px-3 py-2 overflow-x-auto">
          <Plane className="h-3.5 w-3.5 shrink-0 mr-1" />
          <span className="whitespace-nowrap">
            {routeChain.join(' → ')}
          </span>
        </div>
      )}

      {/* Leg slots with drag-and-drop reorder */}
      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={slotIds} strategy={verticalListSortingStrategy}>
          <div className="space-y-3">
            <AnimatePresence initial={false}>
              {slots.map((slot, idx) => (
                <LegSlotCard
                  key={slot.id}
                  slot={slot}
                  index={idx}
                  totalSlots={slots.length}
                  onUpdateFlight={(patch) => updateSlotFlight(slot.id, patch)}
                  onToggleExpanded={() => toggleSlotExpanded(slot.id)}
                  onChangeTransport={(type) => changeTransportType(slot.id, type)}
                  onRemove={!slot.isAutoGenerated ? () => removeSlot(slot.id) : undefined}
                  onMarkArrival={() => markDestinationArrival(slot.id)}
                  onMarkDeparture={() => markDestinationDeparture(slot.id)}
                  showStarControls={slots.length >= 2}
                />
              ))}
            </AnimatePresence>
          </div>
        </SortableContext>
      </DndContext>

      {/* Add another flight */}
      <Button
        variant="ghost"
        size="sm"
        className="text-xs text-muted-foreground hover:text-foreground w-full"
        onClick={addCustomLeg}
      >
        <Plus className="h-3.5 w-3.5 mr-1.5" />
        Add another flight (connecting, etc.)
      </Button>
    </div>
  );
}

// ─────────────────────────────────────────────
// Individual Leg Slot Card
// ─────────────────────────────────────────────

interface LegSlotCardProps {
  slot: FlightLegSlot;
  index: number;
  totalSlots: number;
  onUpdateFlight: (patch: Partial<ManualFlightEntry>) => void;
  onToggleExpanded: () => void;
  onChangeTransport: (type: LegTransportType) => void;
  onRemove?: () => void;
  onMarkArrival?: () => void;
  onMarkDeparture?: () => void;
  showStarControls?: boolean;
}

function LegSlotCard({ slot, index, totalSlots, onUpdateFlight, onToggleExpanded, onChangeTransport, onRemove, onMarkArrival, onMarkDeparture, showStarControls }: LegSlotCardProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: slot.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    zIndex: isDragging ? 50 : undefined,
    opacity: isDragging ? 0.5 : 1,
  };
  const Icon = TRANSPORT_ICONS[slot.transportType];
  const isNonFlight = slot.transportType !== 'flight';

  const legTypeColors: Record<string, string> = {
    outbound: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
    intercity: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20',
    return: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20',
    custom: 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20',
  };

  return (
    <div ref={setNodeRef} style={style}>
    <motion.div
      initial={{ opacity: 0, height: 0 }}
      animate={{ opacity: 1, height: 'auto' }}
      exit={{ opacity: 0, height: 0 }}
      className={cn("border border-border rounded-lg overflow-hidden", slot.flight.isDestinationArrival && "ring-1 ring-primary/30")}
    >
      {/* Header */}
      <div className="flex items-center">
        {/* Drag handle */}
        <div
          {...attributes}
          {...listeners}
          className="px-1.5 py-3 cursor-grab active:cursor-grabbing text-muted-foreground hover:text-foreground"
        >
          <GripVertical className="h-4 w-4" />
        </div>
      <button
        type="button"
        onClick={onToggleExpanded}
        className="flex-1 flex items-center gap-3 pr-4 py-3 hover:bg-muted/50 transition-colors text-left"
      >
        <div className={cn('flex items-center justify-center w-7 h-7 rounded-full border', legTypeColors[slot.legType])}>
          <Icon className="h-3.5 w-3.5" />
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-foreground truncate">{slot.label}</span>
            <Badge variant="outline" className="text-[10px] shrink-0">
              {TRANSPORT_LABELS[slot.transportType]}
            </Badge>
          </div>
          {/* Summary line when collapsed */}
          {!slot.isExpanded && slot.flight.departureAirport && (
            <div className="text-xs text-muted-foreground mt-0.5">
              {slot.flight.departureAirport}
              {slot.connectionLegs && slot.connectionLegs.length > 0 
                ? ` → ${slot.flight.arrivalAirport} → ${slot.connectionLegs.map(c => c.arrivalAirport).join(' → ')}`
                : ` → ${slot.flight.arrivalAirport}`}
              {slot.flight.departureTime && ` · ${slot.flight.departureTime}`}
              {slot.flight.airline && ` · ${slot.flight.airline}`}
              {slot.connectionLegs && slot.connectionLegs.length > 0 && (
                <span className="ml-1 text-primary">(via {slot.flight.arrivalAirport})</span>
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-1">
          {onRemove && (
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0 text-muted-foreground hover:text-destructive"
              onClick={(e) => { e.stopPropagation(); onRemove(); }}
            >
              <Trash2 className="h-3.5 w-3.5" />
            </Button>
          )}
          {slot.isExpanded ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
        </div>
      </button>
      </div>{/* end header flex */}

      {/* Star controls for marking destination arrival / departure */}
      {showStarControls && totalSlots >= 2 && (
        <div className="flex items-center gap-2 px-4 pb-2 pt-1">
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); onMarkArrival?.(); }}
            className={cn(
              "inline-flex items-center gap-1.5 text-[11px] px-2.5 py-1 rounded-md border transition-colors",
              slot.flight.isDestinationArrival
                ? "bg-primary/10 border-primary/30 text-primary font-medium"
                : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/50"
            )}
          >
            <MapPin className={cn("h-3 w-3", slot.flight.isDestinationArrival && "text-primary")} />
            {slot.flight.isDestinationArrival ? 'Destination arrival ✓' : 'Mark as destination arrival'}
          </button>
          <button
            type="button"
            onClick={(e) => { e.stopPropagation(); onMarkDeparture?.(); }}
            className={cn(
              "inline-flex items-center gap-1.5 text-[11px] px-2.5 py-1 rounded-md border transition-colors",
              slot.flight.isDestinationDeparture
                ? "bg-accent/80 border-accent text-accent-foreground font-medium"
                : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/50"
            )}
          >
            <Plane className={cn("h-3 w-3", slot.flight.isDestinationDeparture && "text-accent-foreground")} />
            {slot.flight.isDestinationDeparture ? 'Departure from dest ✓' : 'Mark as departure from destination'}
          </button>
        </div>
      )}
      {/* Expanded content */}
      {slot.isExpanded && (
        <div className="px-4 pb-4 space-y-3 border-t border-border pt-3">
          {/* Transport type switcher for inter-city legs */}
          {slot.legType === 'intercity' && (
            <div className="flex items-center gap-1.5">
              <span className="text-xs text-muted-foreground mr-1">Mode:</span>
              {(Object.keys(TRANSPORT_ICONS) as LegTransportType[]).map(type => {
                const TypeIcon = TRANSPORT_ICONS[type];
                return (
                  <button
                    key={type}
                    type="button"
                    onClick={() => onChangeTransport(type)}
                    className={cn(
                      'flex items-center gap-1 px-2 py-1 rounded-md text-xs border transition-colors',
                      slot.transportType === type
                        ? 'bg-primary/10 border-primary/30 text-primary font-medium'
                        : 'border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/50'
                    )}
                  >
                    <TypeIcon className="h-3 w-3" />
                    {TRANSPORT_LABELS[type]}
                  </button>
                );
              })}
            </div>
          )}

          {/* Non-flight message */}
          {isNonFlight && (
            <div className="text-xs text-muted-foreground bg-muted/50 rounded-lg p-3">
              This leg uses {TRANSPORT_LABELS[slot.transportType].toLowerCase()} transport. 
              Times are optional but help us plan your day.
            </div>
          )}

          {/* Route */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label className="text-xs text-muted-foreground">From</Label>
              {slot.transportType === 'flight' ? (
                <AirportAutocomplete
                  value={slot.flight.departureAirport || slot.suggestedFrom || ''}
                  onChange={(code) => onUpdateFlight({ departureAirport: code })}
                  placeholder={slot.suggestedFrom || 'Airport'}
                />
              ) : (
                <Input
                  placeholder={`Station / Terminal`}
                  value={slot.flight.departureAirport}
                  onChange={(e) => onUpdateFlight({ departureAirport: e.target.value })}
                  className="text-sm"
                />
              )}
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">To</Label>
              {slot.transportType === 'flight' ? (
                <AirportAutocomplete
                  value={slot.flight.arrivalAirport || slot.suggestedTo || ''}
                  onChange={(code) => onUpdateFlight({ arrivalAirport: code })}
                  placeholder={slot.suggestedTo || 'Airport'}
                />
              ) : (
                <Input
                  placeholder={`Station / Terminal`}
                  value={slot.flight.arrivalAirport}
                  onChange={(e) => onUpdateFlight({ arrivalAirport: e.target.value })}
                  className="text-sm"
                />
              )}
            </div>
          </div>

          {/* Date & Times */}
          <div className="grid grid-cols-3 gap-3">
            <div>
              <Label className="text-xs text-muted-foreground">Date</Label>
              <Input
                type="date"
                value={slot.flight.departureDate}
                onChange={(e) => onUpdateFlight({ departureDate: e.target.value })}
                className="text-sm"
              />
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">Departs</Label>
              <Input
                type="time"
                value={slot.flight.departureTime}
                onChange={(e) => onUpdateFlight({ departureTime: e.target.value })}
                className="text-sm"
              />
            </div>
            <div>
              <Label className="text-xs text-muted-foreground">Arrives</Label>
              <Input
                type="time"
                value={slot.flight.arrivalTime}
                onChange={(e) => onUpdateFlight({ arrivalTime: e.target.value })}
                className="text-sm"
              />
            </div>
          </div>

          {/* Airline & flight number (only for flight type) */}
          {slot.transportType === 'flight' && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs text-muted-foreground">Airline</Label>
                <AirlineAutocomplete
                  value={slot.flight.airline}
                  onChange={(val) => onUpdateFlight({ airline: val })}
                  placeholder="e.g. Delta"
                />
              </div>
              <div>
                <Label className="text-xs text-muted-foreground">Flight #</Label>
                <Input
                  placeholder="e.g. DL123"
                  value={slot.flight.flightNumber}
                  onChange={(e) => onUpdateFlight({ flightNumber: e.target.value })}
                  className="text-sm"
                />
              </div>
            </div>
          )}

          {/* Operator for non-flight */}
          {isNonFlight && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs text-muted-foreground">Operator</Label>
                <Input
                  placeholder={slot.transportType === 'train' ? 'e.g. Eurostar' : 'Operator name'}
                  value={slot.flight.airline}
                  onChange={(e) => onUpdateFlight({ airline: e.target.value })}
                  className="text-sm"
                />
              </div>
              <div>
                <Label className="text-xs text-muted-foreground">Booking ref</Label>
                <Input
                  placeholder="Reference #"
                  value={slot.flight.flightNumber}
                  onChange={(e) => onUpdateFlight({ flightNumber: e.target.value })}
                  className="text-sm"
                />
              </div>
            </div>
          )}
        </div>
      )}
    </motion.div>
    </div>
  );
}
