/**
 * Consumer PDF Generator
 * 
 * Uses html2canvas to capture the rendered itinerary DOM,
 * then slices it into A4 pages via jsPDF.
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { format } from 'date-fns';
import type { EditorialDay } from '@/components/itinerary/EditorialItinerary';

export interface ConsumerTripPdfData {
  tripName?: string;
  destination: string;
  startDate: string;
  endDate: string;
  travelers: number;
  days?: EditorialDay[];
  flight?: {
    airline: string;
    departure: string;
    arrival: string;
    departureAirport: string;
    arrivalAirport: string;
  };
  hotel?: {
    name: string;
    neighborhood: string;
    checkIn: string;
    checkOut: string;
  };
}

const fmtDateLong = (s: string) => {
  try { return format(new Date(s), 'EEEE, MMMM d, yyyy'); } catch { return s; }
};

const fmtDate = (s: string) => {
  try { return format(new Date(s), 'EEE, MMM d'); } catch { return s; }
};

/**
 * Build an off-screen HTML element that represents a clean, print-ready itinerary,
 * render it to canvas, and output as a paginated PDF.
 */
export async function generateConsumerTripPdf(data: ConsumerTripPdfData): Promise<void> {
  // Build a temporary container with inline styles (no CSS dependencies)
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed; top: -99999px; left: -99999px;
    width: 794px; /* A4 at 96dpi */
    background: white;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    color: #1a1a2e;
    padding: 0;
    z-index: -1;
  `;

  const accentColor = '#4f46e5';
  const mutedColor = '#888';
  const bodyColor = '#333';

  // ── COVER ──────────────────────────────────────────────────────
  let coverHtml = `
    <div style="padding: 60px 50px 40px; text-align: center; min-height: 600px; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <div style="width: 100%; height: 4px; background: ${accentColor}; margin-bottom: 60px; border-radius: 2px;"></div>
      <h1 style="font-size: 38px; font-weight: 700; margin: 0 0 12px; color: #1a1a2e; letter-spacing: -0.5px;">${escapeHtml(data.destination)}</h1>
  `;

  if (data.tripName && data.tripName !== data.destination && !data.tripName.includes(data.destination)) {
    coverHtml += `<p style="font-size: 16px; color: ${mutedColor}; margin: 0 0 8px;">${escapeHtml(data.tripName)}</p>`;
  }

  coverHtml += `
      <p style="font-size: 14px; color: ${bodyColor}; margin: 16px 0 6px;">${fmtDateLong(data.startDate)} &ndash; ${fmtDateLong(data.endDate)}</p>
      <p style="font-size: 13px; color: ${mutedColor}; margin: 0 0 30px;">${data.travelers} traveler${data.travelers !== 1 ? 's' : ''}</p>
      <div style="width: 40px; height: 1px; background: #ccc; margin: 0 auto 30px;"></div>
  `;

  // Quick reference
  if (data.flight || data.hotel) {
    coverHtml += `<div style="background: #f5f6f8; border-radius: 8px; padding: 20px 28px; text-align: left; max-width: 500px; width: 100%;">`;
    if (data.flight) {
      coverHtml += `
        <p style="font-size: 10px; font-weight: 700; color: ${mutedColor}; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 4px;">Flight</p>
        <p style="font-size: 13px; color: #1a1a2e; margin: 0 0 2px;">${escapeHtml(data.flight.airline)} &middot; ${escapeHtml(data.flight.departureAirport)} &rarr; ${escapeHtml(data.flight.arrivalAirport)}</p>
        <p style="font-size: 12px; color: ${mutedColor}; margin: 0 0 14px;">Departs ${escapeHtml(data.flight.departure)} &middot; Arrives ${escapeHtml(data.flight.arrival)}</p>
      `;
    }
    if (data.hotel) {
      coverHtml += `
        <p style="font-size: 10px; font-weight: 700; color: ${mutedColor}; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 4px;">Hotel</p>
        <p style="font-size: 13px; color: #1a1a2e; margin: 0 0 2px;">${escapeHtml(data.hotel.name)} &middot; ${escapeHtml(data.hotel.neighborhood)}</p>
        <p style="font-size: 12px; color: ${mutedColor}; margin: 0;">${escapeHtml(data.hotel.checkIn)} &ndash; ${escapeHtml(data.hotel.checkOut)}</p>
      `;
    }
    coverHtml += `</div>`;
  }

  coverHtml += `
      <p style="font-size: 10px; color: #aaa; margin-top: 50px;">Generated by Voyance &middot; travelwithvoyance.com</p>
    </div>
  `;

  // ── ITINERARY DAYS ─────────────────────────────────────────────
  let daysHtml = '';
  if (data.days && data.days.length > 0) {
    daysHtml += `
      <div style="padding: 40px 50px;">
        <h2 style="font-size: 22px; font-weight: 700; color: #1a1a2e; margin: 0 0 8px;">Your Itinerary</h2>
        <div style="width: 100%; height: 2px; background: ${accentColor}; margin-bottom: 30px; border-radius: 1px;"></div>
    `;

    for (const day of data.days) {
      const dateStr = day.date ? fmtDate(day.date) : '';
      const theme = day.title || day.theme || '';

      daysHtml += `
        <div style="margin-bottom: 28px;">
          <div style="background: ${accentColor}; color: white; border-radius: 6px; padding: 10px 16px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px;">
            <div>
              <span style="font-weight: 700; font-size: 14px; margin-right: 16px;">Day ${day.dayNumber}</span>
              <span style="font-size: 13px; opacity: 0.9;">${escapeHtml(theme)}</span>
            </div>
            <span style="font-size: 12px; opacity: 0.85;">${escapeHtml(dateStr)}</span>
          </div>
      `;

      if (day.activities && day.activities.length > 0) {
        for (const act of day.activities) {
          const timeStr = act.startTime || act.time || '';
          const locationName = act.location?.name || act.location?.address || '';
          const metaParts: string[] = [];
          if (locationName) metaParts.push(locationName);
          if (act.duration) metaParts.push(act.duration);
          if (act.cost?.amount) metaParts.push(`${act.cost.currency || '$'}${act.cost.amount}`);

          daysHtml += `
            <div style="display: flex; gap: 12px; margin-bottom: 14px; padding-bottom: 12px; border-bottom: 1px solid #f0f0f3;">
              <div style="width: 50px; flex-shrink: 0; text-align: right;">
                ${timeStr ? `<span style="font-size: 12px; font-weight: 700; color: ${accentColor};">${escapeHtml(timeStr)}</span>` : ''}
              </div>
              <div style="flex: 1; min-width: 0;">
                <p style="font-size: 13px; font-weight: 700; color: #1a1a2e; margin: 0 0 3px;">${escapeHtml(act.title)}</p>
                ${act.description ? `<p style="font-size: 11px; color: ${bodyColor}; margin: 0 0 4px; line-height: 1.5;">${escapeHtml(act.description)}</p>` : ''}
                ${metaParts.length > 0 ? `<p style="font-size: 10px; color: ${mutedColor}; margin: 0 0 2px;">${metaParts.map(escapeHtml).join(' &middot; ')}</p>` : ''}
                ${act.tips ? `<p style="font-size: 10px; color: ${accentColor}; margin: 2px 0 0; font-style: italic;">Tip: ${escapeHtml(act.tips)}</p>` : ''}
              </div>
            </div>
          `;
        }
      } else {
        daysHtml += `<p style="font-size: 12px; color: ${mutedColor}; padding-left: 62px;">Free day — explore at your own pace</p>`;
      }

      daysHtml += `</div>`; // close day
    }

    daysHtml += `</div>`; // close itinerary section
  }

  // ── NOTES PAGE ─────────────────────────────────────────────────
  let notesHtml = `
    <div style="padding: 40px 50px; min-height: 500px;">
      <h2 style="font-size: 20px; font-weight: 700; color: #1a1a2e; margin: 0 0 12px;">Notes</h2>
      <div style="width: 100%; height: 1px; background: #ddd; margin-bottom: 16px;"></div>
  `;
  for (let i = 0; i < 22; i++) {
    notesHtml += `<div style="width: 100%; height: 1px; background: #f0f0f3; margin-bottom: 22px;"></div>`;
  }
  notesHtml += `</div>`;

  container.innerHTML = coverHtml + daysHtml + notesHtml;
  document.body.appendChild(container);

  try {
    // Render to canvas at 2x for quality
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      width: 794,
      windowWidth: 794,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfW = pdf.internal.pageSize.getWidth();   // 210
    const pdfH = pdf.internal.pageSize.getHeight();   // 297

    const imgW = pdfW - 10; // 5mm margin each side
    const imgH = (canvas.height * imgW) / canvas.width;

    let heightLeft = imgH;
    let position = 5; // top margin

    // First page
    pdf.addImage(imgData, 'PNG', 5, position, imgW, imgH);
    heightLeft -= (pdfH - 10);

    // Subsequent pages
    while (heightLeft > 0) {
      pdf.addPage();
      position = -(imgH - heightLeft) + 5;
      pdf.addImage(imgData, 'PNG', 5, position, imgW, imgH);
      heightLeft -= (pdfH - 10);
    }

    // Add page numbers
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(170, 170, 170);
      pdf.text('Voyance', 10, pdfH - 6);
      pdf.text(`${i} / ${totalPages}`, pdfW - 10, pdfH - 6, { align: 'right' });
    }

    const safeName = (data.tripName || data.destination).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    pdf.save(`${safeName}-itinerary.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
