/**
 * Consumer PDF Generator — Editorial Design
 *
 * Native jsPDF drawing for selectable text, precise page breaks,
 * and a premium editorial travel document aesthetic.
 */

import jsPDF from 'jspdf';
import { format } from 'date-fns';
import type { EditorialDay } from '@/components/itinerary/EditorialItinerary';

export interface ConsumerTripPdfData {
  tripName?: string;
  destination: string;
  startDate: string;
  endDate: string;
  travelers: number;
  days?: EditorialDay[];
  unlockedDayNumbers?: Set<number>;
  flights?: Array<{
    airline: string;
    departureTime: string;
    arrivalTime: string;
    departureAirport: string;
    arrivalAirport: string;
    date?: string;
    label?: string;
  }>;
  /** @deprecated Use flights[] instead */
  flight?: {
    airline: string;
    departure: string;
    arrival: string;
    departureAirport: string;
    arrivalAirport: string;
  };
  hotel?: {
    name: string;
    neighborhood: string;
    checkIn: string;
    checkOut: string;
  };
}

// ── Color palette (RGB) ──────────────────────────────────────
const C = {
  cream:    [250, 248, 243] as [number, number, number],
  gold:     [184, 151, 106] as [number, number, number],
  charcoal: [61,  52,  36]  as [number, number, number],
  body:     [85,  85,  85]  as [number, number, number],
  muted:    [153, 153, 153] as [number, number, number],
  white:    [255, 255, 255] as [number, number, number],
  lockGray: [156, 163, 175] as [number, number, number],
  cardBg:   [245, 243, 238] as [number, number, number],
  tipBg:    [252, 250, 246] as [number, number, number],
  separator:[230, 225, 215] as [number, number, number],
};

// ── Layout constants ─────────────────────────────────────────
const PW = 210;           // A4 width mm
const PH = 297;           // A4 height mm
const M  = 22;            // side margin
const CW = PW - M * 2;   // content width
const HEADER_Y = 16;
const CONTENT_TOP = 28;
const PAGE_BOTTOM = PH - 18;

// ── Date helpers ─────────────────────────────────────────────
const fmtLong = (s: string) => { try { return format(new Date(s), 'EEEE, MMMM d, yyyy'); } catch { return s; } };
const fmtShort = (s: string) => { try { return format(new Date(s), 'EEE, MMM d'); } catch { return s; } };

// ── Main export ──────────────────────────────────────────────
export async function generateConsumerTripPdf(data: ConsumerTripPdfData): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  let pageNum = 0;

  // ── Helpers ──────────────────────────────────────────────
  const setFont = (style: 'normal' | 'bold' | 'italic' | 'bolditalic', size: number, color: [number, number, number] = C.charcoal) => {
    pdf.setFont('helvetica', style);
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
  };

  const drawCreamBg = () => {
    pdf.setFillColor(...C.cream);
    pdf.rect(0, 0, PW, PH, 'F');
  };

  const drawPageHeader = () => {
    pageNum++;
    // "VOYANCE" wordmark top-left
    setFont('bold', 8, C.gold);
    pdf.text('VOYANCE', M, HEADER_Y);
    // Page number top-right
    setFont('normal', 8, C.muted);
    pdf.text(`${pageNum}`, PW - M, HEADER_Y, { align: 'right' });
    // Gold rule
    pdf.setDrawColor(...C.gold);
    pdf.setLineWidth(0.3);
    pdf.line(M, HEADER_Y + 3, PW - M, HEADER_Y + 3);
  };

  const drawPageFooter = () => {
    const fy = PH - 10;
    pdf.setDrawColor(...C.gold);
    pdf.setLineWidth(0.2);
    pdf.line(M, fy - 2, PW - M, fy - 2);
    setFont('normal', 7, C.muted);
    pdf.text('Generated by Voyance  \u00B7  travelwithvoyance.com', PW / 2, fy, { align: 'center' });
  };

  const newContentPage = (): number => {
    pdf.addPage();
    drawCreamBg();
    drawPageHeader();
    drawPageFooter();
    return CONTENT_TOP;
  };

  const checkBreak = (y: number, needed: number): number => {
    if (y + needed > PAGE_BOTTOM) {
      return newContentPage();
    }
    return y;
  };

  const wrapText = (text: string, maxW: number, size: number, style: 'normal' | 'bold' | 'italic' = 'normal'): string[] => {
    pdf.setFont('helvetica', style);
    pdf.setFontSize(size);
    return pdf.splitTextToSize(text, maxW);
  };

  // ════════════════════════════════════════════════════════
  // COVER PAGE
  // ════════════════════════════════════════════════════════
  drawCreamBg();
  pageNum++;

  let y = 55;

  // Top gold rule + diamond
  pdf.setDrawColor(...C.gold);
  pdf.setLineWidth(0.4);
  const diamondX = PW / 2;
  pdf.line(M + 10, y, diamondX - 8, y);
  pdf.line(diamondX + 8, y, PW - M - 10, y);
  // Diamond shape
  pdf.setFillColor(...C.gold);
  const ds = 2.5;
  pdf.triangle(diamondX, y - ds, diamondX + ds, y, diamondX, y + ds, 'F');
  pdf.triangle(diamondX, y - ds, diamondX - ds, y, diamondX, y + ds, 'F');

  y += 12;

  // "V O Y A N C E" wordmark
  setFont('bold', 14, C.gold);
  pdf.text('V  O  Y  A  N  C  E', PW / 2, y, { align: 'center' });

  y += 30;

  // Destination name
  setFont('bold', 32, C.charcoal);
  const destLines = wrapText(data.destination.toUpperCase(), CW - 20, 32, 'bold');
  for (const line of destLines) {
    pdf.text(line, PW / 2, y, { align: 'center' });
    y += 14;
  }

  // Gold accent line
  y += 4;
  pdf.setDrawColor(...C.gold);
  pdf.setLineWidth(0.6);
  pdf.line(PW / 2 - 20, y, PW / 2 + 20, y);

  y += 14;

  // Dates
  setFont('normal', 10, C.body);
  pdf.text(`${fmtLong(data.startDate)}  \u2013  ${fmtLong(data.endDate)}`, PW / 2, y, { align: 'center' });
  y += 7;

  // Travelers & days
  const dayCount = data.days?.length || 0;
  const metaStr = `${data.travelers} traveler${data.travelers !== 1 ? 's' : ''}${dayCount > 0 ? `  \u00B7  ${dayCount} days` : ''}`;
  setFont('normal', 9, C.muted);
  pdf.text(metaStr, PW / 2, y, { align: 'center' });

  y += 20;

  // ── Accommodation card ───────────────────────────────
  const drawInfoCard = (label: string, lines: string[], startY: number): number => {
    const cardH = 28 + lines.length * 5;
    const cardX = M + 20;
    const cardW = CW - 40;

    pdf.setFillColor(...C.cardBg);
    pdf.roundedRect(cardX, startY, cardW, cardH, 3, 3, 'F');

    setFont('bold', 7, C.gold);
    pdf.text(label, cardX + 10, startY + 10);

    setFont('bold', 11, C.charcoal);
    pdf.text(lines[0] || '', cardX + 10, startY + 18);

    for (let i = 1; i < lines.length; i++) {
      setFont('normal', 9, C.body);
      pdf.text(lines[i], cardX + 10, startY + 18 + i * 6);
    }

    return startY + cardH + 8;
  };

  if (data.hotel) {
    y = drawInfoCard('ACCOMMODATION', [
      data.hotel.name,
      `${data.hotel.neighborhood}`,
      `Check-in: ${data.hotel.checkIn}  \u00B7  Check-out: ${data.hotel.checkOut}`,
    ], y);
  }

  // ── Flight card(s) — supports multiple legs ────────────
  const flightLegs = data.flights ?? (data.flight ? [{
    airline: data.flight.airline,
    departureTime: data.flight.departure,
    arrivalTime: data.flight.arrival,
    departureAirport: data.flight.departureAirport,
    arrivalAirport: data.flight.arrivalAirport,
  }] : []);

  if (flightLegs.length > 0) {
    const cardX = M + 20;
    const cardW = CW - 40;
    const legHeight = 22;
    const cardPadTop = 12;
    const cardPadBot = 8;
    const cardH = cardPadTop + flightLegs.length * legHeight + cardPadBot;

    y = checkBreak(y, cardH);

    pdf.setFillColor(...C.cardBg);
    pdf.roundedRect(cardX, y, cardW, cardH, 3, 3, 'F');

    setFont('bold', 7, C.gold);
    pdf.text(flightLegs.length > 1 ? 'FLIGHTS' : 'FLIGHT', cardX + 10, y + 9);

    let legY = y + cardPadTop + 6;
    for (const leg of flightLegs) {
      // Label (e.g. "Outbound" / "Return")
      if (leg.label) {
        setFont('bold', 7, C.muted);
        pdf.text(leg.label.toUpperCase(), cardX + 10, legY - 3);
      }

      // Airline
      const airline = leg.airline?.trim();
      if (airline) {
        setFont('bold', 11, C.charcoal);
        pdf.text(airline, cardX + 10, legY);
      }

      // Route: DEP to ARR  (using " to " instead of →)
      const dep = leg.departureAirport?.trim();
      const arr = leg.arrivalAirport?.trim();
      if (dep || arr) {
        const route = [dep, arr].filter(Boolean).join('  to  ');
        setFont('normal', 9, C.body);
        const routeX = airline ? cardX + 10 + pdf.getTextWidth(airline + '   ') : cardX + 10;
        if (airline) {
          // put route on same line after airline
          pdf.text(route, routeX, legY);
        } else {
          setFont('bold', 11, C.charcoal);
          pdf.text(route, cardX + 10, legY);
        }
      }

      // Times
      const depTime = leg.departureTime?.trim();
      const arrTime = leg.arrivalTime?.trim();
      const datePart = leg.date?.trim();
      const timeParts: string[] = [];
      if (depTime) timeParts.push(`Departs ${depTime}`);
      if (arrTime) timeParts.push(`Arrives ${arrTime}`);
      if (datePart) timeParts.push(datePart);

      if (timeParts.length > 0) {
        setFont('normal', 9, C.body);
        pdf.text(timeParts.join('  \u00B7  '), cardX + 10, legY + 7);
      }

      legY += legHeight;
    }

    y += cardH + 8;
  }

  // Cover footer ornament
  const footY = PH - 30;
  pdf.setDrawColor(...C.gold);
  pdf.setLineWidth(0.3);
  pdf.line(M + 30, footY, diamondX - 6, footY);
  pdf.line(diamondX + 6, footY, PW - M - 30, footY);
  pdf.setFillColor(...C.gold);
  pdf.triangle(diamondX, footY - 2, diamondX + 2, footY, diamondX, footY + 2, 'F');
  pdf.triangle(diamondX, footY - 2, diamondX - 2, footY, diamondX, footY + 2, 'F');

  setFont('normal', 7, C.muted);
  pdf.text('Generated by Voyance  \u00B7  travelwithvoyance.com', PW / 2, footY + 8, { align: 'center' });

  // ════════════════════════════════════════════════════════
  // ITINERARY PAGES
  // ════════════════════════════════════════════════════════
  if (data.days && data.days.length > 0) {
    y = newContentPage();

    // Section heading
    setFont('bold', 20, C.charcoal);
    pdf.text('Your Itinerary', M, y + 4);
    y += 8;
    pdf.setDrawColor(...C.gold);
    pdf.setLineWidth(0.5);
    pdf.line(M, y, PW - M, y);
    y += 10;

    for (const day of data.days) {
      const isDayLocked = data.unlockedDayNumbers != null && !data.unlockedDayNumbers.has(day.dayNumber);
      const dateStr = day.date ? fmtShort(day.date) : '';
      const theme = day.title || day.theme || '';

      // Estimate day height for page break
      const dayHeaderH = 14;
      let estDayH = dayHeaderH;
      if (isDayLocked) {
        estDayH += 30;
      } else if (day.activities && day.activities.length > 0) {
        estDayH += 20; // min for first activity
      } else {
        estDayH += 12;
      }
      y = checkBreak(y, Math.min(estDayH, 50));

      // ── Day header ──────────────────────────────────
      const headerColor = isDayLocked ? C.lockGray : C.charcoal;
      pdf.setFillColor(...headerColor);
      pdf.roundedRect(M, y, CW, 10, 2, 2, 'F');

      setFont('bold', 11, C.white);
      pdf.text(`Day ${day.dayNumber}`, M + 6, y + 7);

      if (theme) {
        setFont('normal', 9, C.white);
        const themeMaxW = CW - 80;
        const truncTheme = theme.length > 40 ? theme.substring(0, 37) + '...' : theme;
        pdf.text(truncTheme, M + 30, y + 7);
      }

      if (dateStr) {
        setFont('normal', 9, C.white);
        pdf.text(dateStr, PW - M - 6, y + 7, { align: 'right' });
      }

      y += 14;

      if (isDayLocked) {
        // ── Locked day placeholder ──────────────────
        y = checkBreak(y, 24);
        pdf.setDrawColor(...C.lockGray);
        pdf.setLineWidth(0.4);
        // Dashed border
        const dashRect = { x: M + 4, y: y, w: CW - 8, h: 20 };
        pdf.setLineDashPattern([2, 2], 0);
        pdf.rect(dashRect.x, dashRect.y, dashRect.w, dashRect.h);
        pdf.setLineDashPattern([], 0);

        setFont('bold', 10, C.lockGray);
        pdf.text(`Day ${day.dayNumber} is locked`, PW / 2, y + 9, { align: 'center' });
        setFont('normal', 8, C.muted);
        pdf.text('Unlock this day at travelwithvoyance.com to see full details', PW / 2, y + 15, { align: 'center' });

        y += 28;
      } else if (day.activities && day.activities.length > 0) {
        // ── Activities ──────────────────────────────
        for (let ai = 0; ai < day.activities.length; ai++) {
          const act = day.activities[ai];
          const timeStr = act.startTime || act.time || '';
          const locationName = act.location?.name || act.location?.address || '';
          const metaParts: string[] = [];
          if (locationName) metaParts.push(locationName);
          if (act.duration) metaParts.push(act.duration);
          if (act.cost?.amount) metaParts.push(`${act.cost.currency || '$'}${act.cost.amount}`);

          // Estimate activity height
          const descLines = act.description ? wrapText(act.description, CW - 30, 9) : [];
          const tipLines = act.tips ? wrapText(`Tip: ${act.tips}`, CW - 36, 8.5, 'italic') : [];
          let actH = 8; // title
          actH += descLines.length * 4;
          if (metaParts.length > 0) actH += 5;
          if (tipLines.length > 0) actH += tipLines.length * 3.5 + 4;
          actH += 6; // separator + spacing

          y = checkBreak(y, actH);

          const leftCol = 20; // time column width

          // Time
          if (timeStr) {
            setFont('bold', 10, C.gold);
            pdf.text(timeStr, M + 2, y + 4);
          }

          // Title
          setFont('bold', 11, C.charcoal);
          pdf.text(act.title, M + leftCol, y + 4);
          y += 8;

          // Description
          if (descLines.length > 0) {
            setFont('normal', 9, C.body);
            for (const line of descLines) {
              pdf.text(line, M + leftCol, y);
              y += 4;
            }
            y += 1;
          }

          // Meta line
          if (metaParts.length > 0) {
            setFont('normal', 8, C.muted);
            pdf.text(metaParts.join('  \u00B7  '), M + leftCol, y);
            y += 5;
          }

          // Tip box
          if (tipLines.length > 0) {
            y += 1;
            const tipStartY = y;
            // Gold left border
            pdf.setDrawColor(...C.gold);
            pdf.setLineWidth(0.8);
            pdf.line(M + leftCol, tipStartY - 1, M + leftCol, tipStartY + tipLines.length * 3.5 + 1);

            setFont('italic', 8.5, C.gold);
            for (const line of tipLines) {
              pdf.text(line, M + leftCol + 4, y);
              y += 3.5;
            }
            y += 2;
          }

          // Separator line (except last activity)
          if (ai < day.activities.length - 1) {
            y += 2;
            pdf.setDrawColor(...C.separator);
            pdf.setLineWidth(0.15);
            pdf.line(M + leftCol, y, PW - M, y);
            y += 4;
          } else {
            y += 4;
          }
        }
      } else {
        // No activities
        setFont('normal', 9, C.muted);
        pdf.text('Free day \u2014 explore at your own pace', M + 6, y + 2);
        y += 10;
      }

      y += 6; // gap between days
    }
  }

  // ════════════════════════════════════════════════════════
  // NOTES PAGE
  // ════════════════════════════════════════════════════════
  y = newContentPage();

  setFont('bold', 18, C.charcoal);
  pdf.text('Notes', M, y + 4);
  y += 10;
  pdf.setDrawColor(...C.gold);
  pdf.setLineWidth(0.3);
  pdf.line(M, y, PW - M, y);
  y += 14;

  // Ruled lines
  pdf.setDrawColor(...C.separator);
  pdf.setLineWidth(0.1);
  for (let i = 0; i < 22; i++) {
    if (y > PAGE_BOTTOM - 5) break;
    pdf.line(M, y, PW - M, y);
    y += 11;
  }

  // ── Save ───────────────────────────────────────────────
  const safeName = (data.tripName || data.destination).replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  pdf.save(`${safeName}-itinerary.pdf`);
}
