/**
 * Consumer PDF Generator
 * 
 * Generates a clean, branded PDF for consumer trip summaries.
 * Adapted from tripPdfGenerator for non-agent use cases.
 */

import jsPDF from 'jspdf';
import { format } from 'date-fns';
import type { EditorialDay, EditorialActivity } from '@/components/itinerary/EditorialItinerary';

export interface ConsumerTripPdfData {
  tripName?: string;
  destination: string;
  startDate: string;
  endDate: string;
  travelers: number;
  days?: EditorialDay[];
  flight?: {
    airline: string;
    departure: string;
    arrival: string;
    departureAirport: string;
    arrivalAirport: string;
  };
  hotel?: {
    name: string;
    neighborhood: string;
    checkIn: string;
    checkOut: string;
  };
}

// Color constants (RGB)
const COLORS = {
  primary: [99, 102, 241] as [number, number, number],     // Indigo
  dark: [30, 41, 59] as [number, number, number],          // Slate 800
  muted: [100, 116, 139] as [number, number, number],      // Slate 500
  light: [241, 245, 249] as [number, number, number],      // Slate 100
};

export async function generateConsumerTripPdf(data: ConsumerTripPdfData): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper functions
  const addText = (
    text: string, 
    fontSize: number, 
    fontStyle: 'normal' | 'bold' = 'normal', 
    color: [number, number, number] = COLORS.dark
  ) => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    pdf.setTextColor(...color);
    const lines = pdf.splitTextToSize(text, contentWidth);
    pdf.text(lines, margin, y);
    y += lines.length * (fontSize * 0.4) + 3;
  };

  const addCenteredText = (
    text: string,
    fontSize: number,
    fontStyle: 'normal' | 'bold' = 'normal',
    color: [number, number, number] = COLORS.dark
  ) => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    pdf.setTextColor(...color);
    pdf.text(text, pageWidth / 2, y, { align: 'center' });
    y += fontSize * 0.4 + 3;
  };

  const checkPageBreak = (neededSpace: number = 30) => {
    if (y > pageHeight - neededSpace) {
      pdf.addPage();
      y = margin;
      addFooter();
    }
  };

  const addFooter = () => {
    const footerY = pageHeight - 10;
    pdf.setFontSize(8);
    pdf.setTextColor(...COLORS.muted);
    pdf.text(
      `Generated by Voyance • ${format(new Date(), 'MMM d, yyyy')}`,
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );
  };

  // ===== HEADER =====
  pdf.setFillColor(...COLORS.primary);
  pdf.rect(0, 0, pageWidth, 50, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(data.tripName || `Trip to ${data.destination}`, margin, 25);
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  const dateRange = `${format(new Date(data.startDate), 'MMMM d')} – ${format(new Date(data.endDate), 'MMMM d, yyyy')}`;
  pdf.text(`${dateRange} • ${data.travelers} traveler${data.travelers > 1 ? 's' : ''}`, margin, 38);
  
  y = 65;

  // ===== TRIP OVERVIEW =====
  addText('TRIP OVERVIEW', 10, 'bold', COLORS.muted);
  y += 3;
  
  pdf.setDrawColor(...COLORS.light);
  pdf.setLineWidth(0.5);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  if (data.flight) {
    addText('Flight', 11, 'bold');
    addText(`${data.flight.airline} • ${data.flight.departureAirport} → ${data.flight.arrivalAirport}`, 10, 'normal', COLORS.muted);
    addText(`Departure: ${data.flight.departure} | Arrival: ${data.flight.arrival}`, 10, 'normal', COLORS.muted);
    y += 5;
  }

  if (data.hotel) {
    addText('Accommodation', 11, 'bold');
    addText(`${data.hotel.name} • ${data.hotel.neighborhood}`, 10, 'normal', COLORS.muted);
    addText(`Check-in: ${data.hotel.checkIn} | Check-out: ${data.hotel.checkOut}`, 10, 'normal', COLORS.muted);
    y += 5;
  }

  // ===== ITINERARY =====
  if (data.days && data.days.length > 0) {
    y += 10;
    addText('YOUR ITINERARY', 10, 'bold', COLORS.muted);
    y += 3;
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;

    for (const day of data.days) {
      checkPageBreak(40);
      
      // Day header - use title or theme
      const dayTitle = day.title || day.theme || `Day ${day.dayNumber}`;
      pdf.setFillColor(...COLORS.light);
      pdf.rect(margin, y - 4, contentWidth, 10, 'F');
      addText(`Day ${day.dayNumber}: ${dayTitle}`, 12, 'bold');
      
      if (day.date) {
        addText(format(new Date(day.date), 'EEEE, MMMM d'), 9, 'normal', COLORS.muted);
      }
      y += 3;

      // Activities
      for (const activity of day.activities || []) {
        checkPageBreak(15);
        
        const timeStr = activity.startTime ? `${activity.startTime} ` : '';
        addText(`${timeStr}${activity.title}`, 10, 'bold');
        
        if (activity.description) {
          addText(activity.description, 9, 'normal', COLORS.muted);
        }
        
        // Use location.name or location.address for neighborhood
        const locationName = activity.location?.name || activity.location?.address;
        if (locationName) {
          addText(`📍 ${locationName}`, 8, 'normal', COLORS.muted);
        }
        y += 2;
      }
      y += 5;
    }
  }

  // Add footer to first page
  addFooter();

  // Download
  const filename = `${(data.tripName || data.destination).replace(/[^a-z0-9]/gi, '-').toLowerCase()}-itinerary.pdf`;
  pdf.save(filename);
}
