INSERT INTO public.cost_reference (destination_city, destination_country, category, subcategory, item_name, cost_low_usd, cost_mid_usd, cost_high_usd, source, confidence, notes) VALUES
('_global', '_global', 'accommodation', 'budget',  'Budget hotel (per night)',   60,  100,  160, 'reference_seed', 'low', 'Global fallback rate'),
('_global', '_global', 'accommodation', 'mid',     'Mid-range hotel (per night)',150, 250,  400, 'reference_seed', 'low', 'Global fallback rate'),
('_global', '_global', 'accommodation', 'luxury',  'Luxury hotel (per night)',   400, 700, 1200, 'reference_seed', 'low', 'Global fallback rate'),
('Paris', 'France', 'accommodation', 'budget', 'Budget hotel (per night)',   80, 130,  200, 'reference_seed', 'medium', NULL),
('Paris', 'France', 'accommodation', 'mid',    'Mid-range hotel (per night)',180, 300,  500, 'reference_seed', 'medium', NULL),
('Paris', 'France', 'accommodation', 'luxury', 'Luxury hotel (per night)',   600, 950, 1500, 'reference_seed', 'medium', 'Includes Four Seasons, Ritz, Le Meurice tier'),
('London', 'United Kingdom', 'accommodation', 'budget', 'Budget hotel (per night)',   90, 140,  220, 'reference_seed', 'medium', NULL),
('London', 'United Kingdom', 'accommodation', 'mid',    'Mid-range hotel (per night)',200, 320,  520, 'reference_seed', 'medium', NULL),
('London', 'United Kingdom', 'accommodation', 'luxury', 'Luxury hotel (per night)',   600, 950, 1500, 'reference_seed', 'medium', NULL),
('New York', 'United States', 'accommodation', 'budget', 'Budget hotel (per night)',  100, 160,  240, 'reference_seed', 'medium', NULL),
('New York', 'United States', 'accommodation', 'mid',    'Mid-range hotel (per night)',250, 400,  600, 'reference_seed', 'medium', NULL),
('New York', 'United States', 'accommodation', 'luxury', 'Luxury hotel (per night)',   650,1000, 1700, 'reference_seed', 'medium', NULL),
('Tokyo', 'Japan', 'accommodation', 'budget', 'Budget hotel (per night)',   70, 120,  180, 'reference_seed', 'medium', NULL),
('Tokyo', 'Japan', 'accommodation', 'mid',    'Mid-range hotel (per night)',180, 280,  450, 'reference_seed', 'medium', NULL),
('Tokyo', 'Japan', 'accommodation', 'luxury', 'Luxury hotel (per night)',   500, 800, 1300, 'reference_seed', 'medium', NULL),
('Rome', 'Italy', 'accommodation', 'budget', 'Budget hotel (per night)',   70, 110,  170, 'reference_seed', 'medium', NULL),
('Rome', 'Italy', 'accommodation', 'mid',    'Mid-range hotel (per night)',150, 240,  400, 'reference_seed', 'medium', NULL),
('Rome', 'Italy', 'accommodation', 'luxury', 'Luxury hotel (per night)',   500, 800, 1300, 'reference_seed', 'medium', NULL),
('Barcelona', 'Spain', 'accommodation', 'budget', 'Budget hotel (per night)',   60, 100,  160, 'reference_seed', 'medium', NULL),
('Barcelona', 'Spain', 'accommodation', 'mid',    'Mid-range hotel (per night)',140, 230,  380, 'reference_seed', 'medium', NULL),
('Barcelona', 'Spain', 'accommodation', 'luxury', 'Luxury hotel (per night)',   450, 750, 1200, 'reference_seed', 'medium', NULL),
('Dubai', 'United Arab Emirates', 'accommodation', 'budget', 'Budget hotel (per night)',   80, 130,  200, 'reference_seed', 'medium', NULL),
('Dubai', 'United Arab Emirates', 'accommodation', 'mid',    'Mid-range hotel (per night)',180, 300,  500, 'reference_seed', 'medium', NULL),
('Dubai', 'United Arab Emirates', 'accommodation', 'luxury', 'Luxury hotel (per night)',   600,1000, 1800, 'reference_seed', 'medium', NULL),
('Singapore', 'Singapore', 'accommodation', 'budget', 'Budget hotel (per night)',   80, 130,  200, 'reference_seed', 'medium', NULL),
('Singapore', 'Singapore', 'accommodation', 'mid',    'Mid-range hotel (per night)',180, 280,  450, 'reference_seed', 'medium', NULL),
('Singapore', 'Singapore', 'accommodation', 'luxury', 'Luxury hotel (per night)',   500, 800, 1300, 'reference_seed', 'medium', NULL),
('Hong Kong', 'Hong Kong', 'accommodation', 'budget', 'Budget hotel (per night)',   80, 130,  200, 'reference_seed', 'medium', NULL),
('Hong Kong', 'Hong Kong', 'accommodation', 'mid',    'Mid-range hotel (per night)',180, 280,  450, 'reference_seed', 'medium', NULL),
('Hong Kong', 'Hong Kong', 'accommodation', 'luxury', 'Luxury hotel (per night)',   500, 800, 1300, 'reference_seed', 'medium', NULL),
('Bangkok', 'Thailand', 'accommodation', 'budget', 'Budget hotel (per night)',   30,  60,  100, 'reference_seed', 'medium', NULL),
('Bangkok', 'Thailand', 'accommodation', 'mid',    'Mid-range hotel (per night)', 80, 140,  240, 'reference_seed', 'medium', NULL),
('Bangkok', 'Thailand', 'accommodation', 'luxury', 'Luxury hotel (per night)',   300, 500,  900, 'reference_seed', 'medium', NULL),
('Beijing', 'China', 'accommodation', 'budget', 'Budget hotel (per night)',   40,  80,  130, 'reference_seed', 'medium', NULL),
('Beijing', 'China', 'accommodation', 'mid',    'Mid-range hotel (per night)',100, 180,  300, 'reference_seed', 'medium', NULL),
('Beijing', 'China', 'accommodation', 'luxury', 'Luxury hotel (per night)',   350, 600, 1100, 'reference_seed', 'medium', NULL),
('Shanghai', 'China', 'accommodation', 'budget', 'Budget hotel (per night)',   40,  80,  130, 'reference_seed', 'medium', NULL),
('Shanghai', 'China', 'accommodation', 'mid',    'Mid-range hotel (per night)',110, 190,  320, 'reference_seed', 'medium', NULL),
('Shanghai', 'China', 'accommodation', 'luxury', 'Luxury hotel (per night)',   400, 650, 1200, 'reference_seed', 'medium', NULL),
('Austin', 'United States', 'accommodation', 'budget', 'Budget hotel (per night)',   80, 130,  200, 'reference_seed', 'medium', NULL),
('Austin', 'United States', 'accommodation', 'mid',    'Mid-range hotel (per night)',170, 270,  430, 'reference_seed', 'medium', NULL),
('Austin', 'United States', 'accommodation', 'luxury', 'Luxury hotel (per night)',   400, 650, 1100, 'reference_seed', 'medium', NULL);